### ISSUE TITLE
Future & ideas

### ISSUE THREAD

**Issue by dumblob** [TheRealMichaelWang/minima#10]
Interesting language (I kind of like the "messy" conceptual goal :wink:). I have many questions. I'll ask them incrementally on the go.

1. any plans for concurrency (ideally one leveraging multiple CPU cores)?
2. what are the basic types (i.e. platform independent) everything (especially composites/objects/...) builds upon? (I'd like to identify the extent to which metaprogramming is possible in this language)
3. any general performance benchmark measurements? (ideally the state-of-the-art https://github.com/kostya/benchmarks/ )
4. any FFI support which wouldn't need any manual work (no wrapping, no type definitions, nothing - just try to call it and either it succeeds or it sigsegv/dumps_core/etc.)

**Comment by TheRealMichaelWang** [comment]
Thanks for your feedback! As for your questions…

1. There are plans to remodel the virtual machine so it can support multithreading. Most likely it will just use the C standard library’s pthread. Although it should be noted that several new op codes will have to be added to the instruction set. This could probably take a while. 
2. Everything in Minima is either a double, char, array, or record. Though it is possible to modify the source and add types, it’s not something I would recommend doing. If you want to implement a custom “type”, you could use record and operator overloads to do so ([see this example](https://github.com/TheRealMichaelWang/minima/wiki/Operator-Overloading)). Meta programming is practically non-existent in Minima, as it doesn’t support macros.
3. There’s a Conway’s game of life benchmark that simulates 1000 gens on a 10x10 matrix of cells. Other than the Fibonacci example in the README, there aren’t any performance benchmarks. 
4. At this point, there is no FFI support, mainly because of its impact on portability. However there is an API in Minima’s source to add C sourced functions.

And as always, feel free to ask as many questions as you want!

**Comment by dumblob** [comment]
Ok, great. I think most of my other questions are somehow related to the previous ones. But judging based on your answers I think I'll postpone them for a more relevant time point :wink:.

Feel free to close this issue (I'll reopen once I find the time has come :wink:) or leave it open as you see fit.
